- name: Install packages
  hosts: localhost
  vars:
    # kernel_longterm: false # Install the longterm kernel from copr
    with_nvidia: true # Install the nvidia drivers and kernel modules
  tasks:

    - name: Install longterm kernel
      ansible.builtin.shell: |
        set -oeux pipefail
        {{ buildroot }}/scripts/kernel-installer.sh
      args:
        executable: /bin/bash
      changed_when: false
      when: kernel_longterm|bool

    - name: Get kernel version
      ansible.builtin.shell: |
        echo $(ls /usr/lib/modules/)
      register: kernel_query
      failed_when: kernel_query.rc != 0
      changed_when: false

    - name: Set kernel version
      ansible.builtin.set_fact:
        kernel_version: "{{ kernel_query.stdout }}"

    - name: Install Nvidia kernel modules
      ansible.builtin.copy:
        src: "/tmp/builder/nvidia/{{ kernel_version }}/{{ item }}"
        dest: "/usr/lib/modules/{{ kernel_version }}/kernel/drivers/video/"
        mode: "0755"
      loop:
        - nvidia-drm.ko
        - nvidia-modeset.ko
        - nvidia-peermem.ko
        - nvidia-uvm.ko
        - nvidia.ko
      when: with_nvidia

    - name: Kernel depmod
      ansible.builtin.shell: |
        depmod {{ kernel_version }}
      register: result
      failed_when: result.rc != 0
      changed_when: false
      when: with_nvidia

    - name: Install ansible dnf
      ansible.builtin.shell: |
        dnf install -y python3-dnf
        exit $(python -c "import dnf")
      register: ec
      failed_when: ec.rc != 0
      changed_when: false

    - name: Install new packages
      ansible.builtin.dnf:
        name:
          - bootc
          - btop
          - distrobox
          - hwinfo
          - fswatch
          - fzf
          - htop
          - ifuse
          - inxi
          - kitty
          - libva-utils
          - libtree-sitter
          - lm_sensors
          - material-icons-fonts
          - nvidia-vaapi-driver
          - nvtop
          - opencl-filesystem
          - plymouth-theme-spinfinity
          - ripgrep
          - samba
          - stow
          - vdpauinfo
          - xclip
          # - xorg-x11-drv-amdgpu
          - zsh
        state: present

    - name: Install development packages
      ansible.builtin.dnf:
        name:
          - binutils
          - cmake
          - cpp
          - gcc
          - g++
          - git
          - glibc-devel
          - kernel-headers
          - libstdc++-devel
          - make
          - patch
          - SDL2-devel
          - SDL3-devel
          - spirv-tools
          - fd-find
          - fswatch
          - luarocks
          - ninja-build
          - meson
          - nodejs-npm
        state: present


    - name: Remove packages
      ansible.builtin.dnf:
        name:
          - firefox
          - firefox-langpacks
          - virtualbox-guest-additions # because of the dependencies on the kernel package
        state: absent

    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: true

    - name: Install Nvidia drivers
      ansible.builtin.shell: |
        set -oeux pipefail
        {{ buildroot }}/scripts/nvidia-installer.sh
      register: result
      failed_when: result.rc != 0
      changed_when: false
      when: with_nvidia

    - name: Cleanup container
      ansible.builtin.shell: |
        rm -rf /tmp/*
        rm -rf /var/*
        dnf -y clean all
        exit 0
      register: result
      failed_when: result.rc != 0
      changed_when: false
