# https://unix.stackexchange.com/questions/734403/how-can-i-install-xone-xbox-dongle-drivers-in-fedora-silverblue
#
ARG BASE_IMAGE="${BASE_IMAGE}"
ARG FEDORA_MAJOR_VERSION="${FEDORA_MAJOR_VERSION}"

FROM ${BASE_IMAGE}:${FEDORA_MAJOR_VERSION} as xone-builder

RUN ln -s /usr/bin/lld /usr/bin/ld
WORKDIR /tmp

RUN ln -s /usr/bin/rpm-ostree /usr/bin/dnf

ADD build-xone.sh /tmp/build-xone.sh
ADD certs /tmp/certs

RUN /tmp/build-xone.sh
