TARGET_IMAGE_NAME=perpixel-silverblue
BASE_IMAGE=quay.io/fedora-ostree-desktops/silverblue
FEDORA_VERSION=41
USE_LTS_KERNEL=true
NVIDIA_VERSION_BETA=565.57.01
NVIDIA_VERSION_FEATURE=560.35.03
NVIDIA_VERSION_STABLE=550.135
NVIDIA_VERSION=${NVIDIA_VERSION_BETA}
