name: prune repo

on:
  workflow_call:
  
jobs:
  clean-ghcr:
    name: Cleanup repo
    runs-on: ubuntu-latest    
    steps:
    
      - name: Delete old container
        uses: snok/container-retention-policy@v3.1.0
        with:
          image-names: perpixel-silverblue
          cut-off: 1w
          account: user
          image-tags: "!latest"
          token: ${{ secrets.PAT }}

      - name: Delete pr containers
        uses: snok/container-retention-policy@v3.1.0
        with:
          image-names: perpixel-silverblue
          cut-off: 1d
          account: user
          image-tags: "pr-*"
          token: ${{ secrets.PAT }}
