name: prune repo

on:
  workflow_call:

jobs:
  clean-ghcr:
    name: Cleanup repo
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

      - name: Delete old container versions
        uses: snok/container-retention-policy@v3.1.0
        with:
          image-names: perpixel-silverblue
          cut-off: 1w
          account: user
          keep-n-most-recent: 3
          token: ${{ github.token }}
